require: rubocop-rails

AllCops:
  Excludes:
    - bin/*
    - config/**/*
    - spec/**/*
    - db/**/*

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods