version: '3.1'
services:
  db:
    image: postgres:10.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
  web:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ~/.ssh:/root/.ssh
      - bundle_cache:/bundle
      - .:/pomodoro_sheet_api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
volumes:
  postgres_data: {}
  bundle_cache: {}
